name: Ensure Version Match Between package.json and src/version.ts

on:
  pull_request:
    types: [opened, synchronize]
    branches: ["main"]


jobs:
  ensure-version-match:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Ensure version match
      run: |
        LIB_VERSION=$(cat src/version.ts | grep LIB_VERSION | cut -d'=' -f2 | sed 's/[" '"'"';]//g')
        PACKAGE_JSON_VERSION=$(jq -r '.version' package.json)
        if [ "$LIB_VERSION" != "$PACKAGE_JSON_VERSION" ]; then
          echo "Version mismatch between src/version.ts and package.json"
          echo "LIB_VERSION: $LIB_VERSION"
          echo "PACKAGE_JSON_VERSION: $PACKAGE_JSON_VERSION"
          exit 1
        fi
        echo "Version match between src/version.ts and package.json"
